/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthNuevaClaveRouteImport } from './routes/auth.nueva-clave'
import { Route as LegalPaginaRouteImport } from './routes/legal.$pagina'
import { Route as PanelIndexRouteImport } from './routes/panel.index'
import { Route as PanelCartaRouteImport } from './routes/panel.carta'
import { Route as PanelEmpezarRouteImport } from './routes/panel.empezar'
import { Route as PanelLocalRouteImport } from './routes/panel.local'
import { Route as PanelPublicarRouteImport } from './routes/panel.publicar'
import { Route as QCodigoRouteImport } from './routes/q.$codigo'
import { Route as PanelImportarIndexRouteImport } from './routes/panel.importar.index'
import { Route as PanelImportarIdRouteImport } from './routes/panel.importar.$id'
import { Route as PanelPlatoIdRouteImport } from './routes/panel.plato.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthNuevaClaveRoute = AuthNuevaClaveRouteImport.update({
  id: '/auth/nueva-clave',
  path: '/auth/nueva-clave',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPaginaRoute = LegalPaginaRouteImport.update({
  id: '/legal/$pagina',
  path: '/legal/$pagina',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelIndexRoute = PanelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PanelRoute,
} as any)
const PanelCartaRoute = PanelCartaRouteImport.update({
  id: '/carta',
  path: '/carta',
  getParentRoute: () => PanelRoute,
} as any)
const PanelEmpezarRoute = PanelEmpezarRouteImport.update({
  id: '/empezar',
  path: '/empezar',
  getParentRoute: () => PanelRoute,
} as any)
const PanelLocalRoute = PanelLocalRouteImport.update({
  id: '/local',
  path: '/local',
  getParentRoute: () => PanelRoute,
} as any)
const PanelPublicarRoute = PanelPublicarRouteImport.update({
  id: '/publicar',
  path: '/publicar',
  getParentRoute: () => PanelRoute,
} as any)
const QCodigoRoute = QCodigoRouteImport.update({
  id: '/q/$codigo',
  path: '/q/$codigo',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelImportarIndexRoute = PanelImportarIndexRouteImport.update({
  id: '/importar/',
  path: '/importar/',
  getParentRoute: () => PanelRoute,
} as any)
const PanelImportarIdRoute = PanelImportarIdRouteImport.update({
  id: '/importar/$id',
  path: '/importar/$id',
  getParentRoute: () => PanelRoute,
} as any)
const PanelPlatoIdRoute = PanelPlatoIdRouteImport.update({
  id: '/plato/$id',
  path: '/plato/$id',
  getParentRoute: () => PanelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/entrar': typeof EntrarRoute
  '/panel': typeof PanelRouteWithChildren
  '/registro': typeof RegistroRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/nueva-clave': typeof AuthNuevaClaveRoute
  '/legal/$pagina': typeof LegalPaginaRoute
  '/panel/carta': typeof PanelCartaRoute
  '/panel/empezar': typeof PanelEmpezarRoute
  '/panel/local': typeof PanelLocalRoute
  '/panel/publicar': typeof PanelPublicarRoute
  '/q/$codigo': typeof QCodigoRoute
  '/panel/': typeof PanelIndexRoute
  '/panel/importar/$id': typeof PanelImportarIdRoute
  '/panel/plato/$id': typeof PanelPlatoIdRoute
  '/panel/importar/': typeof PanelImportarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/entrar': typeof EntrarRoute
  '/registro': typeof RegistroRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/nueva-clave': typeof AuthNuevaClaveRoute
  '/legal/$pagina': typeof LegalPaginaRoute
  '/panel/carta': typeof PanelCartaRoute
  '/panel/empezar': typeof PanelEmpezarRoute
  '/panel/local': typeof PanelLocalRoute
  '/panel/publicar': typeof PanelPublicarRoute
  '/q/$codigo': typeof QCodigoRoute
  '/panel': typeof PanelIndexRoute
  '/panel/importar/$id': typeof PanelImportarIdRoute
  '/panel/plato/$id': typeof PanelPlatoIdRoute
  '/panel/importar': typeof PanelImportarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/entrar': typeof EntrarRoute
  '/panel': typeof PanelRouteWithChildren
  '/registro': typeof RegistroRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/nueva-clave': typeof AuthNuevaClaveRoute
  '/legal/$pagina': typeof LegalPaginaRoute
  '/panel/carta': typeof PanelCartaRoute
  '/panel/empezar': typeof PanelEmpezarRoute
  '/panel/local': typeof PanelLocalRoute
  '/panel/publicar': typeof PanelPublicarRoute
  '/q/$codigo': typeof QCodigoRoute
  '/panel/': typeof PanelIndexRoute
  '/panel/importar/$id': typeof PanelImportarIdRoute
  '/panel/plato/$id': typeof PanelPlatoIdRoute
  '/panel/importar/': typeof PanelImportarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/entrar'
    | '/panel'
    | '/registro'
    | '/auth/callback'
    | '/auth/nueva-clave'
    | '/legal/$pagina'
    | '/panel/carta'
    | '/panel/empezar'
    | '/panel/local'
    | '/panel/publicar'
    | '/q/$codigo'
    | '/panel/'
    | '/panel/importar/$id'
    | '/panel/plato/$id'
    | '/panel/importar/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/entrar'
    | '/registro'
    | '/auth/callback'
    | '/auth/nueva-clave'
    | '/legal/$pagina'
    | '/panel/carta'
    | '/panel/empezar'
    | '/panel/local'
    | '/panel/publicar'
    | '/q/$codigo'
    | '/panel'
    | '/panel/importar/$id'
    | '/panel/plato/$id'
    | '/panel/importar'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/entrar'
    | '/panel'
    | '/registro'
    | '/auth/callback'
    | '/auth/nueva-clave'
    | '/legal/$pagina'
    | '/panel/carta'
    | '/panel/empezar'
    | '/panel/local'
    | '/panel/publicar'
    | '/q/$codigo'
    | '/panel/'
    | '/panel/importar/$id'
    | '/panel/plato/$id'
    | '/panel/importar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  EntrarRoute: typeof EntrarRoute
  PanelRoute: typeof PanelRouteWithChildren
  RegistroRoute: typeof RegistroRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthNuevaClaveRoute: typeof AuthNuevaClaveRoute
  LegalPaginaRoute: typeof LegalPaginaRoute
  QCodigoRoute: typeof QCodigoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/nueva-clave': {
      id: '/auth/nueva-clave'
      path: '/auth/nueva-clave'
      fullPath: '/auth/nueva-clave'
      preLoaderRoute: typeof AuthNuevaClaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$pagina': {
      id: '/legal/$pagina'
      path: '/legal/$pagina'
      fullPath: '/legal/$pagina'
      preLoaderRoute: typeof LegalPaginaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/': {
      id: '/panel/'
      path: '/'
      fullPath: '/panel/'
      preLoaderRoute: typeof PanelIndexRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/carta': {
      id: '/panel/carta'
      path: '/carta'
      fullPath: '/panel/carta'
      preLoaderRoute: typeof PanelCartaRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/empezar': {
      id: '/panel/empezar'
      path: '/empezar'
      fullPath: '/panel/empezar'
      preLoaderRoute: typeof PanelEmpezarRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/local': {
      id: '/panel/local'
      path: '/local'
      fullPath: '/panel/local'
      preLoaderRoute: typeof PanelLocalRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/publicar': {
      id: '/panel/publicar'
      path: '/publicar'
      fullPath: '/panel/publicar'
      preLoaderRoute: typeof PanelPublicarRouteImport
      parentRoute: typeof PanelRoute
    }
    '/q/$codigo': {
      id: '/q/$codigo'
      path: '/q/$codigo'
      fullPath: '/q/$codigo'
      preLoaderRoute: typeof QCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/importar/': {
      id: '/panel/importar/'
      path: '/importar'
      fullPath: '/panel/importar/'
      preLoaderRoute: typeof PanelImportarIndexRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/importar/$id': {
      id: '/panel/importar/$id'
      path: '/importar/$id'
      fullPath: '/panel/importar/$id'
      preLoaderRoute: typeof PanelImportarIdRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/plato/$id': {
      id: '/panel/plato/$id'
      path: '/plato/$id'
      fullPath: '/panel/plato/$id'
      preLoaderRoute: typeof PanelPlatoIdRouteImport
      parentRoute: typeof PanelRoute
    }
  }
}

interface PanelRouteChildren {
  PanelCartaRoute: typeof PanelCartaRoute
  PanelEmpezarRoute: typeof PanelEmpezarRoute
  PanelLocalRoute: typeof PanelLocalRoute
  PanelPublicarRoute: typeof PanelPublicarRoute
  PanelIndexRoute: typeof PanelIndexRoute
  PanelImportarIdRoute: typeof PanelImportarIdRoute
  PanelPlatoIdRoute: typeof PanelPlatoIdRoute
  PanelImportarIndexRoute: typeof PanelImportarIndexRoute
}

const PanelRouteChildren: PanelRouteChildren = {
  PanelCartaRoute: PanelCartaRoute,
  PanelEmpezarRoute: PanelEmpezarRoute,
  PanelLocalRoute: PanelLocalRoute,
  PanelPublicarRoute: PanelPublicarRoute,
  PanelIndexRoute: PanelIndexRoute,
  PanelImportarIdRoute: PanelImportarIdRoute,
  PanelPlatoIdRoute: PanelPlatoIdRoute,
  PanelImportarIndexRoute: PanelImportarIndexRoute,
}

const PanelRouteWithChildren = PanelRoute._addFileChildren(PanelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  EntrarRoute: EntrarRoute,
  PanelRoute: PanelRouteWithChildren,
  RegistroRoute: RegistroRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthNuevaClaveRoute: AuthNuevaClaveRoute,
  LegalPaginaRoute: LegalPaginaRoute,
  QCodigoRoute: QCodigoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
